language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "iojs"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_script:
  - npm install -g gulp
script:
  - gulp test
services:
  - postgresql
env:
  - NODE_ENV=test
before_script:
  - psql -c 'create database school_portal_test;' -U postgres
