language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "iojs"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8  
before_script:
  - npm install -g gulp
script:
  - gulp test
services:
  - postgresql
env:
  - NODE_ENV=test
before_script:
  - psql -c 'create database school_portal_test;' -U postgres
